### PR TITLE
Specific user posts, edit posts, soft delete posts, show read time, show all users as admin

### LINKED ISSUE #4: View Current User's Posts
As an author, I would like to see a list of all the Posts I have written so that I can easily view, edit, delete, publish or unpublish them.

**Given** the user is in the Tabloid application  
**When** they select the `My Posts` menu option  
**Then** they should be directed to the "My Posts" list page  
**And** the page should display ALL the Posts authored by the logged-in user  
**And** each post in the list should display the title, author and category  
**And** the list should be in order of creation date with the most recent on top

### LINKED ISSUE #7: Delete a Post
As an author I would like the ability to remove a post I have written so that I can prevent others from reading it when I decide it is no longer something I wish people to read.

**Given** an author is viewing a Post that they have written  
**When** they select the delete option  
**Then** they should be presented to confirm the deletion    

**Given** the author wishes to confirm the delete  
**When** they the select the option to confirm  
**Then** the Post should be removed from the system  
**And** the author should be directed back to the Post list  

**Given** the author decides not to confirm the delete  
**When** they the select the option to reject confirmation  
**Then** the Post should NOT be removed from the system  
**And** the author should be directed back to the Post details

### LINKED ISSUE #8: Edit a Post
As a author I would like to be able to modify my Posts so that I can correct mistakes or add additional content.

**Given** the user is viewing the Post list  
**When** they select the option to edit an Post  
**Then** the user should be directed to a form and given the ability to change the Post's information  

**Given** the user is finished updating the Post information  
**When** they click the `Save` button  
**Then** the updated Post should be saved to the database  
**And** the user should be redirected to the new Post's details page

**Given** the user has decided not to edit the Post  
**When** they click the `Cancel` button  
**Then** the user should be redirected back to the list page

Editable Information

* Title
* Content
* Category
* Header Image URL (optional)
* Publication Date (optional)

### LINKED ISSUE #23: Display Estimated Read Time on a Post
As a reader, I would like know how much time it will take to read a particular Post so that I can determine whether I have time to read it now or I should save it for later.

**Given** a user is viewing a Post
**When** they look at the "header" information (title, category, publish date, etc...)
**Then** they should see a message indicating approximately how many minutes it will take read the post.

> **NOTE:** Use the calculation found on this page https://help.medium.com/hc/en-us/articles/214991667-Read-time.

> **NOTE:** The calculation should round up to the next minute. For example if the calculation determines that a post should take `4:28` to read, the message should indicate that it will take approximately `5` minutes.

> **NOTE:** If the calculation determines it will take `1` minute to read, the message should use the singular form of the word "minute". It should not say "1 minutes".

### LINKED ISSUE #24: View All User Profiles
As an admin, I would like to see a list of all the User Profiles so that I can keep track of who is using the system.

**Given** the user is an admin in the Tabloid application  
**When** they select the `User Profiles` menu option  
**Then** they should be directed to the User Profiles list page  
**And** each user in the list should display the full name, the display name and the user type.
**And** the list should be in ordered alphabetically by user display name

### PR DESCRIPTION
**Pull request by tylerghilliard94**
# Description
Allows user to see just their posts, edit posts and soft delete posts, Posts now show estimated read time, and admin can see all user profiles.
## Type of change
Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions
Git fetch --all
Git checkout into th-Post/User
Login with admin@example.com
Go to my Posts and you should see only your blog posts.
Click the eye button on a post and at the top right should be the estimated read time.
You can click the pen button to edit the posts and it will redirect you to the post details after you are done.
You can click the trash can to delete posts but they will remain in the database.

If logged in as an admin you should see USER PROFILES menu option at the top of the page. 
Once clicked it should show a list of all users on the platform.
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bstoudt01** [comment]
Everything works but i noticed that Create Post will allow you to add a post.PublishDate for future dates. But the edit method GetPostById(int Id) wont handle having a publish date greater than the system date, causing the edit view to throw an exception with posts having publish dates in the future.

**Review by bstoudt01 — COMMENTED** [review]
Works great,
except for the publishDataTime issue I experienced, noted below

**Review by bstoudt01 — APPROVED** [review]
Works great,
except for the publishDataTime issue I experienced, noted below

**Review by sfreeley — COMMENTED** [review]
Awesome job! Everything works great except for the publish date in the future issue like Brett mentioned. 

Also, I think that maybe we are supposed to see the post details screen if the user decides not to delete a post?

**Review by sfreeley — APPROVED** [review]
Date issue fixed and everything working well!

**Pull request merged**
